spring:
  application:
    name: the-newest-synergy-project
  main:
    banner-mode: 'off'
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_loading_no_trans: true
    hibernate:
      ddl-auto: validate
